// <auto-generated/>
using System.Reflection;

[assembly: AssemblyProductAttribute("Alea.TypeProviders")]
[assembly: AssemblyCompanyAttribute("QuantAlea GmbH.")]
[assembly: AssemblyCopyrightAttribute("QuantAlea GmbH. 2010-2014")]
[assembly: AssemblyVersionAttribute("1.0.743")]
[assembly: AssemblyFileVersionAttribute("1.0.743")]
[assembly: AssemblyInformationalVersionAttribute("1.0.743")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.743";
    }
}
